[sdl]
output=surface
autolock=false

[dosbox]
memsize=512

[cpu]
core=dynamic
cycles=max

[dos]
lfn=true
ver=7.1
keyboardlayout=none

[midi]
mididevice=none

[mixer]
nosound=true

[speaker]
pcspeaker=false
tandy=off
disney=false
ps1audio=off

[ide, primary]
int13fakeio=false
int13fakev86io=false

[autoexec]
mount c "@ROOT@" -nocachedir
mount d "@TOOLS@"
mount r "@REQUEST@" -nocachedir
r:
call run.bat
exit
