@ECHO OFF
C:
SET PATH=C:\BIN;C:\BLD
SET PATH_SEPARATOR=:
SET TMPDIR=C:\TMP
SET TEMP=C:\TMP
SET GO32TMP=C:\TMP
SET XPAR=C:\BLD\XPAR.EXE
SET XPAR_TEST_FIXTURES=C:\SRC\FORMAT
SET XPAR_TEST_LEVEL=@LEVEL@
C:\BLD\TSUITE.EXE --report=C:\RESULT.LOG 2>C:\ERROR.LOG
IF ERRORLEVEL 1 GOTO FAILED
ECHO 0>C:\STATUS.TXT
GOTO FINISH
:FAILED
ECHO 1>C:\STATUS.TXT
:FINISH
C:\BIN\SYNC.EXE
C:\BIN\EXIT.EXE
