name: Build

on: [ push, pull_request ]

jobs:
  dist:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: |
        ./bootstrap && ./configure
    - name: Make source package
      run: make VERSION=${{ github.sha }} dist
    - name: Upload source package artifact
      uses: actions/upload-artifact@v4
      with:
        name: xpar-${{ github.sha }}
        path: xpar-${{ github.sha }}.tar.gz
    - name: Run distcheck
      run: make distcheck

  build:
    name: Compile (clang/gcc, x86_64)
    needs: [ dist ]
    strategy:
      fail-fast: false
      matrix:
        compiler: [ clang, gcc ]
        feature: [ enable-x86_64, disable-x86_64 ]
    runs-on: ubuntu-latest
    steps:
    - name: Download source package artifact
      uses: actions/download-artifact@v4
      with:
        name: xpar-${{ github.sha }}
    - name: Extract source package
      run: tar --strip-components=1 -xf xpar-${{ github.sha}}.tar.gz
    - name: Configure
      run: ./configure CC=${{ matrix.compiler }} --${{ matrix.feature }}
    - name: Make
      run: make
